const dict = {
    "en": {
        "RFID Scanner": "RFID Scanner",
        "Sign in": "Sign in",
        "Signing out…": "Signing out…",
        "Sign out": "Sign out",
        "Home": "Home",
        "Invoices": "Invoices",
        "Products": "Products",
        "Scan Mode": "Scan Mode",
        "SignIn": "SignIn",
        "SignUp": "SignUp",
        "Tags": "Tags",
        "Users": "Users",
        "Handcrafted 22K artistry": "Handcrafted 22K artistry",
        "Heritage Rings": "Heritage Rings",
        "Minimal Necklaces": "Minimal Necklaces",
        "Classic Bracelets": "Classic Bracelets",
        "Search jewelry": "Search jewelry",
        "Timeless Gold by": "Timeless Gold by",
        "KANAN": "KANAN",
        "Discover handcrafted 22K & 18K pieces inspired by heritage motifs and modern minimalism. Designed to be worn for a lifetime.": "Discover handcrafted 22K & 18K pieces inspired by heritage motifs and modern minimalism. Designed to be worn for a lifetime.",
        "NEW SEASON": "NEW SEASON",
        "Book Appointment": "Book Appointment",
        "Shop Collections": "Shop Collections",
        "KANAN • HERITAGE • 22K • 18K • DIAMONDS": "KANAN • HERITAGE • 22K • 18K • DIAMONDS",
        "Featured Collections": "Featured Collections",
        "A curated selection of rings, necklaces, and bracelets — designed in-house and made with ethically sourced gold.": "A curated selection of rings, necklaces, and bracelets — designed in-house and made with ethically sourced gold.",
        "The KANAN Way": "The KANAN Way",
        "Crafted with Purpose": "Crafted with Purpose",
        "Every KANAN piece begins with a sketch and a story. Our artisans bring heritage techniques to contemporary forms, finishing each surface to a soft glow — never brash, always elegant.": "Every KANAN piece begins with a sketch and a story. Our artisans bring heritage techniques to contemporary forms, finishing each surface to a soft glow — never brash, always elegant.",
        "Visit a Boutique": "Visit a Boutique",
        "Our Story": "Our Story",
        "Join the KANAN Circle": "Join the KANAN Circle",
        "Be the first to know about new drops, private previews, and atelier events.": "Be the first to know about new drops, private previews, and atelier events.",
        "Subscribe": "Subscribe",
        "KANAN Gold. All rights reserved.": "KANAN Gold. All rights reserved.",
        "View": "View",
        "Assured Purity": "Assured Purity",
        "BIS-hallmarked & authenticated.": "BIS-hallmarked & authenticated.",
        "Certified": "Certified",
        "GIA/IGI certified stones.": "GIA/IGI certified stones.",
        "Buyback": "Buyback",
        "Lifetime exchange & upgrades.": "Lifetime exchange & upgrades.",
        "Nothing exist to show.": "Nothing exist to show.",
        "Date:": "Date:",
        "No:": "No:",
        "Pay Type:": "Pay Type:",
        "Desc:": "Desc:",
        "Address: Tabriz, Milad Noor": "Address: Tabriz, Milad Noor",
        "PHONE: 09141501251": "PHONE: 09141501251",
        "Kanani jewelry": "Kanani jewelry",
        "Customer:": "Customer:",
        "Name": "Name",
        "No": "No",
        "Quantity": "Quantity",
        "Weight(g)": "Weight(g)",
        "Making Charge + Profit + VAT": "Making Charge + Profit + VAT",
        "Spot Price (ریال)": "Spot Price (ریال)",
        "Total (ریال)": "Total (ریال)",
        "Total Price": "Total Price",
        "Customer Sign": "Customer Sign",
        "Store Sign": "Store Sign",
        "Print": "Print",
        "Cash": "Cash",
        "Credit": "Credit",
        "Search Invoices": "Search Invoices",
        "Something went wrong.": "Something went wrong.",
        "Sort By": "Sort By",
        "Created At": "Created At",
        "Customer Name": "Customer Name",
        "All:": "All:",
        "Detail": "Detail",
        "Items:": "Items:",
        "Total:": "Total:",
        "Load More": "Load More",
        "cash": "cash",
        "credit": "credit",
        "Enter 10–11 digits": "Enter 10–11 digits",
        "Keep typing…": "Keep typing…",
        "Invalid mobile number": "Invalid mobile number",
        "✓ Looks good": "✓ Looks good",
        "Invalid national ID": "Invalid national ID",
        "Enter 10 digits": "Enter 10 digits",
        "Issue": "Issue",
        "product(s) selected.": "product(s) selected.",
        "INVOICE": "INVOICE",
        "Unit Price:": "Unit Price:",
        "Available:": "Available:",
        "Unit Weight:": "Unit Weight:",
        "g": "g",
        "Making Charge:": "Making Charge:",
        "Sold Quantity:": "Sold Quantity:",
        "Sub Type:": "Sub Type:",
        "Inventory Item:": "Inventory Item:",
        "All": "All",
        "Necklace": "Necklace",
        "Ring": "Ring",
        "Bracelet": "Bracelet",
        "Earrings": "Earrings",
        "Pendant": "Pendant",
        "Anklet": "Anklet",
        "Bangle": "Bangle",
        "Chain": "Chain",
        "WatchPendant": "WatchPendant",
        "Piercing": "Piercing",
        "Medal": "Medal",
        "Coin": "Coin",
        "FullSet": "FullSet",
        "HalfSet": "HalfSet",
        "Others": "Others",
        "Out of stock": "Out of stock",
        "User not authenticated, please login": "User not authenticated, please login",
        "Inventory": "Inventory",
        "Scan": "Scan",
        "New Product": "New Product",
        "Scanning IDs": "Scanning IDs",
        "Latest": "Latest",
        "Weight": "Weight",
        "page rows": "page rows",
        "Preview": "Preview",
        "Type": "Type",
        "Unit Price (ریال)": "Unit Price (ریال)",
        "Availability": "Availability",
        "Unit Weight (g)": "Unit Weight (g)",
        "Making Charge": "Making Charge",
        "Sold Qty": "Sold Qty",
        "Sub Type": "Sub Type",
        "Available": "Available",
        "Settings": "Settings",
        "You can see connected Module(s) and re-init them, also you can change modules power of scanning.": "You can see connected Module(s) and re-init them, also you can change modules power of scanning.",
        "An Error accured.": "An Error accured.",
        "New": "New",
        "Fetch Latest State": "Fetch Latest State",
        "Initializing...": "Initializing...",
        "RE-INIT": "RE-INIT",
        "Active": "Active",
        "Disable": "Disable",
        "Search Products": "Search Products",
        "Server Error": "Server Error",
        "Uploading…": "Uploading…",
        "SubType": "SubType",
        "grams": "grams",
        "VAT": "VAT",
        "PROFIT": "PROFIT",
        "Select Tags": "Select Tags",
        "Upload Photos": "Upload Photos",
        "Register Product": "Register Product",
        "Inventory Item": "Inventory Item",
        "Photos": "Photos",
        "NewProduct": "NewProduct",
        "Select RFID Tags": "Select RFID Tags",
        "Cancel": "Cancel",
        "Confirm": "Confirm",
        "Capture Photos from Camera": "Capture Photos from Camera",
        "Capture Photos": "Capture Photos",
        "Captured Photos": "Captured Photos",
        "Email": "Email",
        "Password": "Password",
        "Remember me": "Remember me",
        "Forgot password?": "Forgot password?",
        "Signing in…": "Signing in…",
        "Creating account…": "Creating account…",
        "Don’t have an account?": "Don’t have an account?",
        "Sign up": "Sign up",
        "Create your account": "Create your account",
        "Confirm password": "Confirm password",
        "Already have an account?": "Already have an account?",
        "We’ll sign you in automatically after creating your account.": "We’ll sign you in automatically after creating your account.",
        "Spot Price:": "Spot Price:",
        "Proforma Invoice": "Proforma Invoice",
        "RSSI": "RSSI",
        "EPC": "EPC",
        "edit": "edit",
        "Confirm delete": "Confirm delete",
        "This action cannot be undone. Continue?": "This action cannot be undone. Continue?",
        "Delete": "Delete",
        "Cannot delete: product has related sales.": "Cannot delete: product has related sales.",
        "You are not allowed to delete this product": "You are not allowed to delete this product",
        "Product not found": "Product not found",
        "Save": "Save",
        "Edit Product": "Edit Product",
        "Cannot update: product has related sales.": "Cannot update: product has related sales.",
        "Cannot update: product quantity only can be increased.": "Cannot update: product quantity only can be increased.",
        "You are not allowed to update this product": "You are not allowed to update this product",
        "Invalid credentials": "Invalid credentials",
        "Invalid refresh token": "Invalid refresh token",
        "User not found": "User not found",
        "Insufficient role": "Insufficient role",
        "ids is required": "ids is required",
        "Max 100 ids": "Max 100 ids",
        "Product updated successfully": "Product updated successfully",
        "An error occurred updating product.": "An error occurred updating product.",
        "Product registered successfully": "Product registered successfully",
        "An error occurred submitting new product.": "An error occurred submitting new product.",
        "Failed to generate previews": "Failed to generate previews",
        "tags selected": "tags selected",
        "Backup DB": "Backup DB",
        "DB BACKUP": "DB BACKUP",
        "Reset": "Reset",
        "Apply": "Apply",
        "Price ($)": "Price ($)",
        "Weight (g)": "Weight (g)",
        "Making Charge (%)": "Making Charge (%)",
        "Profit (%)": "Profit (%)",
        "Advanced Filters": "Advanced Filters",
        "Dashboard": "Dashboard",
        "Updated at:": "Updated at:",
        "Gold Price Dashboard": "Gold Price Dashboard",
        "Failed to fetch gold data.": "Failed to fetch gold data.",
        "Failed to fetch dashboard data.": "Failed to fetch dashboard data.",
        "IR_GOLD_18K": "18K Gold",
        "IR_GOLD_24K": "24K Gold",
        "IR_GOLD_MELTED": "Melted Gold",
        "XAUUSD": "Gold Ounce",
        "IR_COIN_1G": "1g Coin",
        "IR_COIN_QUARTER": "Quarter Coin",
        "IR_COIN_HALF": "Half Coin",
        "IR_COIN_EMAMI": "Emami Coin",
        "IR_COIN_BAHAR": "Bahar Azadi Coin",
        "IR_PCOIN_1-5G": "1.5g Parsian Coin",
        "IR_PCOIN_1-4G": "1.4g Parsian Coin",
        "IR_PCOIN_1-3G": "1.3g Parsian Coin",
        "IR_PCOIN_1-2G": "1.2g Parsian Coin",
        "IR_PCOIN_1-1G": "1.1g Parsian Coin",
        "IR_PCOIN_1G": "1g Parsian Coin",
        "IR_PCOIN_900MG": "900mg Parsian Coin",
        "IR_PCOIN_800MG": "800mg Parsian Coin",
        "IR_PCOIN_700MG": "700mg Parsian Coin",
        "IR_PCOIN_600MG": "600mg Parsian Coin",
        "IR_PCOIN_500MG": "500mg Parsian Coin",
        "IR_PCOIN_400MG": "400mg Parsian Coin",
        "IR_PCOIN_300MG": "300mg Parsian Coin",
        "IR_PCOIN_200MG": "200mg Parsian Coin",
        "IR_PCOIN_100MG": "100mg Parsian Coin",
        "IR_PCOIN_70MG": "70mg Parsian Coin",
        "IR_PCOIN_50MG": "50mg Parsian Coin",
        "IR_PCOIN_30MG": "30mg Parsian Coin",
        "Gold Shop Management Dashboard": "Gold Shop Management Dashboard",
        "Daily": "Daily",
        "Monthly": "Monthly",
        "6 Months": "6 Months",
        "Yearly": "Yearly",
        "Number of Sold Items": "Number of Sold Items",
        "Sales Amount": "Sales Amount",
        "Profit": "Profit",
        "Vat": "Vat",
        "Sold Gold Weight (g)": "Sold Gold Weight (g)",
        "Available Gold Weight (g)": "Available Gold Weight (g)",
        "New Customers": "New Customers",
        "customer": "customer",
        "(g)": "(g)",
        "Sold Gold Weight by Gold Type": "Sold Gold Weight by Gold Type",
        "Sold Gold Weight by Gold Sub Type": "Sold Gold Weight by Gold Sub Type",
        "Available Gold Weight by Gold Type": "Available Gold Weight by Gold Type",
        "With Making Charge": "With Making Charge",
        "Available Gold Weight by Gold Sub Type": "Available Gold Weight by Gold Sub Type",
        "Physical": "Physical",
        "total": "total",
        "Top Customers": "Top Customers",
        "Clear localStorage": "Clear localStorage",
        "Reload Window": "Reload Window",
        "Switch to light": "Switch to light",
        "Switch to dark": "Switch to dark",
        "Switch to LTR": "Switch to english",
        "Switch to RTL": "Switch to farsi",
        "Karat": "Karat",
        "IRR": "IRR",
        "accessoriesCharge": "accessoriesCharge",
        "Full Screen": "Full Screen",
        "Connected Modules": "Connected Modules",
        "No ESP32 modules connected.": "No ESP32 modules connected.",
        "s ago": "s ago",
        "m ago": "m ago",
        "h ago": "h ago",
        "clear history": "clear history",
        "You Successfully Scanned All Inventory Items.": "You Successfully Scanned All Inventory Items.",
        "Get Rest Of What Should be scanned.": "Get Rest Of What Should be scanned.",
    },
    "fa": {
        "RFID Scanner": "تگ نما",
        "Sign in": "ورود",
        "Signing out…": "در حال خروج",
        "Sign out": "خروج",
        "Home": "خانه",
        "Invoices": "فاکتورها",
        "Products": "محصولات",
        "Scan Mode": "حالت اسکن",
        "SignIn": "ورود",
        "SignUp": "ثبت نام",
        "Tags": "تگ ها",
        "Users": "کاربران",
        "Handcrafted 22K artistry": "دست ساز هنری",
        "Heritage Rings": "حلقه اصیل",
        "Minimal Necklaces": "گردنبند مینیمال",
        "Classic Bracelets": "دستبند سنتی",
        "Search jewelry": "جستجوی جواهرات",
        "Timeless Gold by": "جواهرات ",
        "KANAN": "کنعان",
        "Discover handcrafted 22K & 18K pieces inspired by heritage motifs and modern minimalism. Designed to be worn for a lifetime.": "قطعات دست‌ساز ۲۲ هزار و ۱۸ هزار دلاری را کشف کنید که با الهام از نقوش قدیمی و مینیمالیسم مدرن ساخته شده‌اند و برای استفاده مادام‌العمر طراحی شده‌اند.",
        "NEW SEASON": "مجموعه جدید",
        "Book Appointment": "رزرو نوبت",
        "Shop Collections": "مجموعه فروشگاه ها",
        "KANAN • HERITAGE • 22K • 18K • DIAMONDS": "کنعان • میراث • الماس • جواهر",
        "Featured Collections": "مجموعه های ویژه",
        "A curated selection of rings, necklaces, and bracelets — designed in-house and made with ethically sourced gold.": "مجموعه‌ای منتخب از انگشترها، گردنبندها و دستبندها - طراحی داخلی و ساخته شده با طلای خالص.",
        "The KANAN Way": "چشم انداز گالری کنعان",
        "Crafted with Purpose": "ساخت هدفمند",
        "Every KANAN piece begins with a sketch and a story. Our artisans bring heritage techniques to contemporary forms, finishing each surface to a soft glow — never brash, always elegant.": "هر قطعه‌ی KANAN با یک طرح و یک داستان آغاز می‌شود. استادکاران ما تکنیک‌های میراثی را به فرم‌های معاصر می‌آورند و هر سطح را تا درخششی نرم پرداخت می‌کنند — پرزرق‌وبرق نباشید، همواره ظریف باشید.",
        "Visit a Boutique": "فروشگاه",
        "Our Story": "درباره ما",
        "Join the KANAN Circle": "عضو باشگاه KANAN شوید",
        "Be the first to know about new drops, private previews, and atelier events.": "اولین نفری باشید که از عرضه‌های جدید، پیش‌نمایش‌های خصوصی و رویدادهای گالری باخبر می‌شود.",
        "Subscribe": "عضویت در خبرنامه",
        "KANAN Gold. All rights reserved.": "کلیه حقوق مادی و معنوی متعلق به گالری کنعان می باشد.",
        "View": "جزئیات",
        "Assured Purity": "خلوصِ تضمین‌شده",
        "BIS-hallmarked & authenticated.": "مُهر استاندارد BIS و اصالتِ تأیید‌شده",
        "Certified": "تأییدشده",
        "GIA/IGI certified stones.": "با تأییدیهٔ GIA/IGI",
        "Buyback": "بازخرید تضمینی",
        "Lifetime exchange & upgrades.": "امکان تعویض و ارتقا برای همیشه",
        "Nothing exist to show.": "هیچ اطلاعاتی یافت نشد.",
        "Date:": "تاریخ",
        "No:": "شماره",
        "Pay Type:": "روش پرداخت",
        "Desc:": "توضیحات",
        "Address: Tabriz, Milad Noor": "آدرس: تبریز، میلاد نور",
        "PHONE: 09141501251": "09141501251",
        "Kanani jewelry": "جواهرات کنعان",
        "Customer:": "مشتری",
        "Name": "نام",
        "No": "ردیف",
        "Quantity": "تعداد",
        "Weight(g)": "وزن (گرم)",
        "Making Charge + Profit + VAT": "اجرت + سود + مالیات",
        "Spot Price (ریال)": "قیمت لحظه ای (ریال)",
        "Total (ریال)": "جمع (ریال)",
        "Total Price": "قیمت نهایی",
        "Customer Sign": "امضا مشتری",
        "Store Sign": "امضا فروشگاه",
        "Print": "چاپ",
        "Cash": "نقدی",
        "Credit": "اعتباری",
        "Search Invoices": "جستجوی فاکتور ها",
        "Something went wrong.": "مشکلی پیش آمد.",
        "Sort By": "بترتیب",
        "Created At": "زمان ایجاد",
        "Customer Name": "نام مشتری",
        "All:": "همه",
        "Detail": "جزئیات",
        "Items:": "اقلام",
        "Total:": "قیمت نهایی",
        "Load More": "بارگزاری بیشتر",
        "cash": "نقدی",
        "credit": "اعتباری",
        "Enter 10–11 digits": "طول کاراکتر های وارده بایستی 10 و یا 11 باشد.",
        "Keep typing…": "تایپ کنید...",
        "Invalid mobile number": "شماره وارده اشتباه می باشد.",
        "✓ Looks good": "✓ صحیح",
        "Invalid national ID": "کد ملی اشتباه می باشد.",
        "Enter 10 digits": "10 رقم وارد نمایید",
        "Issue": "صدور فاکتور",
        "product(s) selected.": "عدد محصول انتخاب شد.",
        "INVOICE": "فاکتور",
        "Unit Price:": "قیمت واحد",
        "Available:": "موجودی",
        "Unit Weight:": "وزن واحد",
        "g": "گرم",
        "Making Charge:": "اجرت",
        "Sold Quantity:": "تعداد فروش",
        "Sub Type:": "نوع جنس طلا:",
        "Inventory Item:": "محصول ویترینی:",
        "All": "همه",
        "Necklace": "گردنبند",
        "Ring": "انگشتر",
        "Bracelet": "دستبند",
        "Earrings": "گوشواره",
        "Pendant": "آویز",
        "Anklet": "پابند",
        "Bangle": "النگو",
        "Chain": "زنجیر",
        "WatchPendant": "آویز ساعت",
        "Piercing": "پیرسینگ",
        "Medal": "مدال",
        "Coin": "سکه",
        "FullSet": "تمام سِت",
        "HalfSet": "نیم سِت",
        "Others": "متفرقه",
        "Out of stock": "اتمام موجودی",
        "User not authenticated, please login": "مشکل احراز هویت، دوباره وارد شوید",
        "Inventory": "ویترین",
        "Scan": "رومیزی",
        "New Product": "محصول جدید",
        "Scanning IDs": "اسکنر های متصل",
        "Latest": "جدید ترین",
        "Weight": "وزن",
        "page rows": "تعداد سطر",
        "Preview": "تصویر",
        "Type": "دسته بندی",
        "Unit Price (ریال)": "قیمت واحد (ریال)",
        "Availability": "موجودی",
        "Unit Weight (g)": "وزن واحد (گرم)",
        "Making Charge": "اجرت",
        "Sold Qty": "تعداد فروخته شده",
        "Sub Type": "نوع جنس طلا",
        "Available": "موجودی",
        "Settings": "تنظیمات",
        "You can see connected Module(s) and re-init them, also you can change modules power of scanning.": "می‌توانید اسکنرهای متصل را ببینید و یا دوباره راه‌اندازی کنید، همچنین می‌توانید توان اسکنرها را تغییر دهید.",
        "An Error accured.": "مشکلی پیش آمد.",
        "New": "جدید",
        "Fetch Latest State": "دریافت آخرین وضعیت اسکنر های متصل",
        "Initializing...": "در حال شناسایی...",
        "RE-INIT": "راه اندازی مجدد",
        "Active": "فعال",
        "Disable": "غیر فعال",
        "Search Products": "جستجوی محصولات",
        "Server Error": "خطای سرور",
        "Uploading…": "در حال بارگزاری...",
        "SubType": "نوع جنس طلا",
        "grams": "گرم",
        "VAT": "مالیات",
        "PROFIT": "سود",
        "Select Tags": "انتخاب تگ ها",
        "Upload Photos": "بارگزاری تصاویر",
        "Register Product": "ثبت محصول",
        "Inventory Item": "محصول ویترینی",
        "Photos": "تصاویر",
        "NewProduct": "محصول جدید",
        "Select RFID Tags": "تگ مورد نظر را انتخاب نمایید",
        "Cancel": "لغو",
        "Confirm": "تایید",
        "Capture Photos from Camera": "استفاده از دوربین",
        "Capture Photos": "عکس گرفتن",
        "Captured Photos": "تصاویر ثبت شده",
        "Email": "پست الکترونیک",
        "Password": "رمز عبور",
        "Remember me": "مرا به خاطر بسپار",
        "Forgot password?": "فراموشی رمز عبور",
        "Signing in…": "در حالت ورود ...",
        "Creating account…": "در حالت ساخت حساب جدید ...",
        "Don’t have an account?": "حساب کاربری ندارید؟",
        "Sign up": "ثبت نام",
        "Create your account": "ایجاد حساب کاربری",
        "Confirm password": "تایید رمز عبور",
        "Already have an account?": "حساب کاربری دارید?",
        "We’ll sign you in automatically after creating your account.": "پس از ثبت حساب کاربری به صورت اتوماتیک وارد خواهید شد. ",
        "Spot Price:": "قیمت لحظه ای",
        "Proforma Invoice": "پیش فاکتور",
        "EPC": "نام تگ",
        "RSSI": "قدرت سیگنال",
        "edit": "ویرایش",
        "Confirm delete": "تاییدیه برای حذف",
        "This action cannot be undone. Continue?": "برای همیشه حذف خواهد شد، مطمئنید؟",
        "Delete": "حذف",
        "Cannot delete: product has related sales.": "امکان حذف محصول به علت فروش محصول مقدور نمی باشد.",
        "You are not allowed to delete this product": "شما مجاز به حذف محصولاتی هستید که توسط خودتان ایجاد شده است.",
        "Product not found": "محصول مورد نظر پیدا نشد",
        "Save": "ذخیره",
        "Edit Product": "ویرایش محصول",
        "Cannot update: product has related sales.": "خطا در بروزرسانی: به علت فروش محصول امکان تغییر مشخصات محصول مقدور نمی باشد.",
        "Cannot update: product quantity only can be increased.": "خطا در بروزرسانی: امکان کاهش موجودی مقدور نیست.",
        "You are not allowed to update this product": "مجوز لازم جهت بروزرسانی محصول را ندارید. کاربری که محصول را ایجاد کرده مجاز به ویرایش می باشد.",
        "Invalid credentials": "اطلاعات وارده اشتباه می باشد",
        "Invalid refresh token": "رفرش توکن معتبر نیست",
        "User not found": "کاربر مورد نظر پیدا نشد",
        "Insufficient role": "مجوز لازم جهت دسترسی به این آیتم را ندارید",
        "ids is required": "ids الزامی است",
        "Max 100 ids": "حداکثر 100 مورد میتوانید وارد کنید",
        "Product updated successfully": "بروزرسانی با موفقیت انجام شد.",
        "An error occurred updating product.": "مشکلی در بروزرسانی پیش آمد.",
        "Product registered successfully": "ثبت محصول با موفقیت انجام شد.",
        "An error occurred submitting new product.": "مشکلی در ثبت محصول جدید رخ داده است.",
        "Failed to generate previews": "مشکلی در ایجاد فایل پیش نمایش رخ داد",
        "tags selected": "تگ انتخاب شد",
        "Backup DB": "پشتیبان گیری",
        "DB BACKUP": "پشتیبان گیری",
        "Reset": "حذف فیلترها",
        "Apply": "اعمال فیلترها",
        "Price ($)": "قیمت (ريال)",
        "Weight (g)": "وزن (گرم)",
        "Making Charge (%)": "اجرت ساخت (%)",
        "Profit (%)": "سود (%)",
        "Advanced Filters": "جستجوی پیشرفته",
        "Dashboard": "داشبورد",
        "Updated at:": "زمان بروزرسانی",
        "Gold Price Dashboard": "تابلوی قیمت طلا",
        "Failed to fetch gold data.": "مشکلی در دریافت اطلاعات بروز طلا پیش آمد.",
        "Failed to fetch dashboard data.": "مشکلی در دریافت اطلاعات بروز طلا پیش آمد.",
        "IR_GOLD_18K": "طلای 18 عیار",
        "IR_GOLD_24K": "طلای 24 عیار",
        "IR_GOLD_MELTED": "طلای آب‌شده نقدی",
        "XAUUSD": "انس طلا",
        "IR_COIN_1G": "سکه یک گرمی",
        "IR_COIN_QUARTER": "ربع سکه",
        "IR_COIN_HALF": "نیم سکه",
        "IR_COIN_EMAMI": "سکه امامی",
        "IR_COIN_BAHAR": "سکه بهار آزادی",
        "IR_PCOIN_1-5G": "سکه 1.5 گرمی پارسیان",
        "IR_PCOIN_1-4G": "سکه 1.4 گرمی پارسیان",
        "IR_PCOIN_1-3G": "سکه 1.3 گرمی پارسیان",
        "IR_PCOIN_1-2G": "سکه 1.2 گرمی پارسیان",
        "IR_PCOIN_1-1G": "سکه 1.1 گرمی پارسیان",
        "IR_PCOIN_1G": "سکه 1 گرمی پارسیان",
        "IR_PCOIN_900MG": "سکه 900 سوتی پارسیان",
        "IR_PCOIN_800MG": "سکه 800 سوتی پارسیان",
        "IR_PCOIN_700MG": "سکه 700 سوتی پارسیان",
        "IR_PCOIN_600MG": "سکه 600 سوتی پارسیان",
        "IR_PCOIN_500MG": "سکه 500 سوتی پارسیان",
        "IR_PCOIN_400MG": "سکه 400 سوتی پارسیان",
        "IR_PCOIN_300MG": "سکه 300 سوتی پارسیان",
        "IR_PCOIN_200MG": "سکه 200 سوتی پارسیان",
        "IR_PCOIN_100MG": "سکه 100 سوتی پارسیان",
        "IR_PCOIN_70MG": "سکه 70 سوتی پارسیان",
        "IR_PCOIN_50MG": "سکه 50 سوتی پارسیان",
        "IR_PCOIN_30MG": "سکه 30 سوتی پارسیان",
        "Gold Shop Management Dashboard": "داشبورد مدیریت طلا فروشی",
        "Daily": "روزانه",
        "Monthly": "ماهانه",
        "6 Months": "شش ماهه",
        "Yearly": "سالانه",
        "Number of Sold Items": "تعداد اقلام فروخته شده",
        "Sales Amount": "میزان فروش",
        "Profit": "سود",
        "Vat": "مالیات",
        "Sold Gold Weight (g)": "گرم طلای فروخته شده",
        "Available Gold Weight (g)": "گرم طلای موجود",
        "New Customers": "مشتریان جدید",
        "customer": "نفر",
        "(g)": "گرم",
        "Sold Gold Weight by Gold Type": "گرم طلای فروخته‌شده به تفکیک نوع طلا",
        "Sold Gold Weight by Gold Sub Type": "گرم طلای فروخته‌شده به تفکیک نوع جنس طلا",
        "Available Gold Weight by Gold Type": "گرم طلای موجود به تفکیک نوع طلا",
        "With Making Charge": "با اجرت",
        "Available Gold Weight by Gold Sub Type": "گرم طلای موجود به تفکیک نوع جنس طلا",
        "Physical": "فیزیکی",
        "total": "کل",
        "Top Customers": "مشتریان برتر",
        "Clear localStorage": "حذف شخصی سازی ها",
        "Reload Window": "بازنشانی صفحه",
        "Switch to light": "تغییر به حالت روز",
        "Switch to dark": "تغییر به حالت شب",
        "Switch to LTR": "تغییر زبان به انگلیسی",
        "Switch to RTL": "تغییر زبان به فارسی",
        "Karat": "عیار",
        "IRR": "ریال",
        "accessoriesCharge": "هزینه اکسسوری",
        "Full Screen": "تمام صفحه",
        "Connected Modules": "ماژول های متصل",
        "No ESP32 modules connected.": "هیچ ماژولی پیدا نشد.",
        "s ago": " ثانیه پیش",
        "m ago": " دقیقه پیش",
        "h ago": " ساعت پیش",
        "clear history": "پاک کردن سابقه اسکن",
        "You Successfully Scanned All Inventory Items.": "تمامی محصولات ویترینی اسکن شد.",
        "Get Rest Of What Should be scanned.": "محصولات ویترینی که اسکن نشده اند.",
    }
}

export const translate = (ln: "en" | "fa") => {
    if (ln === "en") return dict["en"]
    if (ln === "fa") return dict["fa"]

}